                        <th class="stats-colonne">Match</th>
                        <th class="stats-colonne">Min</th>
                        <th class="stats-colonne">Pts</th>
                        <th class="stats-colonne">Passes</th>
                        <th class="stats-colonne">3pts</th>
                        <th class="stats-colonne">5 majeur</th>
                        <th class="stats-colonne">LF</th>
                        <th class="stats-colonne">Rebonds</th>
                        <th class="stats-colonne">Interc.</th>
                        <th class="stats-colonne">Fautes</th>
                        <th class="stats-colonne">V.</th>
                        <th class="stats-colonne">Eval</th>